# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from os.path import expanduser as pexpanduser

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=[pexpanduser('~/usr/include')])
env.NumpyPythonExtension(
        'fftpack_lite',
        LIBS=['ndarray'],
        LIBPATH=[pexpanduser('~/usr/lib')],
        source = ['fftpack_litemodule.c', 'fftpack.c'])
