import os

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=[os.environ['NDARRAY_INC_DIR']])
env.NumpyPythonExtension(
        'fftpack_lite',
        LIBS=['ndarray'],
        LIBPATH=[os.environ['NDARRAY_LIB_DIR']],
        source = ['fftpack_litemodule.c', 'fftpack.c'])
