import os
import sys

from numscons import GetNumpyEnvironment



env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=['numpy', "#$build_prefix/numpy/core/src/private",
                              os.environ['NDARRAY_INC_DIR']])
if sys.platform == 'win32':
    env.Prepend(LIBPATH=[os.environ['NDARRAY_LIB_DIR']])
    env.Prepend(LIBS=['ndarray'])
env.NumpyPythonExtension('_capi', source = ['_capi.c'])
