# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from os.path import expanduser as pexpanduser

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=['numpy', "#$build_prefix/numpy/core/src/private",
                     pexpanduser('~/usr/include')])
env.NumpyPythonExtension('_capi', source = ['_capi.c'])
