import os

from numscons import GetNumpyEnvironment


env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=["#$build_prefix/numpy/core/src/private",
                     os.environ['NDARRAY_INC_DIR']])

env.NumpyPythonExtension(
         '_compiled_base',
         LIBS=['ndarray'],
         LIBPATH=[os.environ['NDARRAY_LIB_DIR']],
         source = ['src/_compiled_base.c'])
