# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from os.path import expanduser as pexpanduser, join as pjoin

from numscons import GetNumpyEnvironment


usr_lib_dir = pjoin(pexpanduser('~'), 'usr', 'lib')
usr_inc_dir = pjoin(pexpanduser('~'), 'usr', 'include')

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=["#$build_prefix/numpy/core/src/private", usr_inc_dir])

env.NumpyPythonExtension(
         '_compiled_base',
         LIBS=['ndarray'],
         LIBPATH=[usr_lib_dir],
         source = ['src/_compiled_base.c'])
