# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from os.path import expanduser as pexpanduser

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=["#$build_prefix/numpy/core/src/private"])
env.NumpyPythonExtension(
         '_compiled_base',
         LIBS=['ndarray'],
         LIBPATH=[pexpanduser('~/usr/lib')],
         source = ['src/_compiled_base.c'])
